openstack-charmers/charm-layer-ovn

lib/charms/ovn_charm.py, reactive/ovn_chassis_charm_handlers.py, unit_tests/test_lib_charms_ovn_charm.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
When deployed with OpenStack, Nova expects the local OVSDB server
to listen to TCP port 6640 on localhost.  This is configurable in
os-vif, but the knob is not exposed through Nova.
Fix indentation level in ``configure_ovs`` method.
Closes-Bug: #1852200
=> chassis: Conditionally add TCP listener on OVSDB

actions/ovn_os_actions.py, reactive/ovn_chassis_charm_handlers.py
The openstack layer [2] has a default implementation of actions which
are implemented in the os_actions modules.  This uses
charms_openstac.bus.discover() to locate and import the concrete charm
class and instantiate it.  This is needed for the default actions to
work.  The linked bug [1] is due to the module charms.ovn_central not
existing as the two dependent charm layers (ovn-chassis and
ovn-dedicated-chassis) implement them in uniquely named modules
(ovn_chassis and ovn_dedicated_chassis).  The bug [1] is fixed by
modifying the charm layers to place their concrete charm class modules
into /lib/charm/openstack upon which everything will 'just work'.
[1] LP bug: https://bugs.launchpad.net/charm-ovn-chassis/+bug/1861069
[2] https://review.opendev.org/p/openstack/charm-layer-openstack
=> Change ovn layer to work with os_actions in openstack layer

config.yaml, lib/charms/ovn_charm.py, reactive/ovn_chassis_charm_handlers.py, unit_tests/test_lib_charms_ovn_charm.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
Replace the `interface-bridge-mappings` configuration option with
a `bridge-interface-mappings` configuration option.
The new configuration option also takes its arguments in the
reverse order of the original.
This is done based on power user feedback and to align with how
existing network charms are configured.  LP: #1850956
=> Change how bridge interface mappings are configured

lib/charms/ovn_charm.py, reactive/ovn_chassis_charm_handlers.py, unit_tests/test_lib_charms_ovn_charm.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
Due to what is probably a bug in Open vSwitch OVS reconfiguration
was gated on certificate changes.  Allow reconfiguration even when
certificate data is not changed.
Remove uneccessary restart of all services on configuration change.
Add gating to not run on update-status where appropriate.
=> Fix OVS reconfiguration, avoid uneccessary restarts

lib/charms/ovn_charm.py, reactive/ovn_chassis_charm_handlers.py, unit_tests/test_lib_charms_ovn_charm.py
At present the code will attempt to deduce a FQDN from a bound IP,
this will most likelly not be what our user wants. Use FQDN built
from official name of the host instead.
Add supporting code for ``data`` extra-binding to choose IP to use
for overlay traffic.
=> Fix handling of chassis system ID and cert req

reactive/ovn_chassis_charm_handlers.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
A select release handler must be enabled in order for the provide
charm class instance magic in `charms.openstack` to work.
Each specialized charm class encapsulates the necessary delta in
code for the charm to operate on a specific release.
=> Enable the default select release handler

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
As an interrim solution this was provided by the charm awaiting
proper delivery through the Ubuntu package.
=> Remove charm provided init script for metadata agent

lib/charms/ovn_charm.py, reactive/ovn_chassis_charm_handlers.py, unit_tests/test_lib_charms_ovn_charm.py
When the charm code executes the default release selector code
will instantiate all incarnations of the non-abstract charm
classes as a side effect of figuring out which one to use.
At present we set the package and service list as class variables,
subsequently the specialized class initializers will extend on
the same variables and we end up with a charm class with an
incorrect package and service specification.
To fix this we assign the package and service variable in the OVN
Charm base class initializer.
We also remove activation of the default select release handler
in the layer as it will execute too late.  Each individual charm
must execute the handler as early as possible.
=> Fix package/service adaption in specialized classes

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
The charm class was supposed to override the default certificate
request handler, but due to a typo it did not.
Be more defensive in the code that writes certificates out to disk.
Even with our certificate request handler in place the charm may
get into situations where there are multiple certificate requests
on the relation.
=> Fix certificate request and response handling

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
At present the `certificates` relation will report as missing
until Vault is equipped with a root CA to issue certificates.
=> Improve messaging for required relations

lib/charms/ovn_charm.py
The parent method will always return a OrderedDict so no need to
check, also removes a incorrect return type.
=> Remove incorrect check and return from states_to_check

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
A part of the migration strategy to OVN is to start the chassis
charms paused only to resume them as soon as cleanup after the
previous SDN has been completed.
For this to work we need to run a full hook execution on resume to
make sure the system is configured properly.
=> Do full hook execution on resume

config.yaml, layer.yaml, lib/charms/ovn_charm.py, metadata.yaml, reactive/ovn_chassis_charm_handlers.py, unit_tests/__init__.py, unit_tests/test_lib_charms_ovn_charm.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
Adds the nrpe-external-master layer and checks for services managed by
this charm.
func-test-pr: https://github.com/openstack-charmers/zaza-openstack-tests/pull/433
Closes-Bug: #1896674
=> Add NRPE checks for services

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
Avoid the call to get_ovs_hostname and LP Bug# 1900457 when there are no
TLS objects. i.e. certificates relation to vault or ssl_* parameters
set.
Closes-Bug: #1900457
=> Deffer TLS processing when there are no TLS objects

config.yaml, lib/charms/ovn_charm.py, templates/interfaces.yaml, unit_tests/test_lib_charms_ovn_charm.py
Populate the sriov-netplan-shim interfaces.yaml config with PCI
address of interfaces. This is necessary as the VFs may be
configured at a time in the boot sequence where interface naming
has not settled yet.
Stop doing runtime reconfiguration of SR-IOV, in addition to being
detrimental to any virtual machine instance consuming the VF this
will break NIC firmware in some configurations.
Merge after:
https://github.com/juju/charm-helpers/pull/549
Closes-Bug: #1908351
=> SR-IOV: match on PCI address, don't do runtime config

lib/charms/ovn_charm.py, tox.ini, unit_tests/test_lib_charms_ovn_charm.py
When the `ovn-chassis` charm is deployed with `new-units-paused=true`,
the `charm.ovn-chassis.enable-openstack` flag is not set because the
handler that sets that flag does not run when units are paused. When
the migration is complete the operator runs a resume on all the
`ovn-chassis` units. This resume in-turn runs a `config-changed` hook
from within the `resume` action. When the `config-changed` hook fires the
previously guarded handler now runs and executes the code that sets
the `charm.ovn-chassis.enable-openstack` state and then runs a
`charm_instance.install()` *1. However the charm instance that
`charm.provide_charm_instance()` provided is cached *2 from a previous
handler. When the first handler ran, which created an instance of the
class, `charm.ovn-chassis.enable-openstack` was …
=> Move OVNChassisCharm propoerties out of __init__

config.yaml, lib/charms/ovn_charm.py, reactive/ovn_chassis_charm_handlers.py, templates/openvswitch-switch, unit_tests/test_lib_charms_ovn_charm.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
By default, mlockall() is enabled for ovs-vswitchd. This results in
locking all of ovs-vswitchd's process memory into physical RAM and
prevents paging. This enables network performance but can lead to
memory exhaustion in memory-constrained environments. To disable
mlockall(), the disable-mlockall charm config option can be set to
True. If unset, disable-mlockall charm config will result in
disabling mlockall if running in a container.
This patch also changes the ordering of config rendering to occur
before configure_ovs() and ensures that if disable-mlockall changes
that openvswitch-switch will be restarted prior to ovs configuration.
Closes-Bug: #1906280
=> Add disable-mlockall config

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
The prior commit that enable disable-mlockall support only restarts
openvswitch-switch when the disable-mlockall config value is changed. It
didn't handle deploy-time restart of openvswitch-switch.
This patch ensures that /etc/default/openvswitch-swith is rendered and
openvswitch-switch is restarted directly after install. This ensures that
when the disable-mlockall config option is unset, mlockall actually gets
disabled when running in a container. See config.yaml description for more
details.
Related-Bug: #1906280
=> Ensure disable-mlockall is handled at deploy time

lib/charms/ovn_charm.py
When openvswitch is restarted it causes ensuing ovn-host restarts
to leak ovn-controller processes. The ovn-host stop/start is needed
until the following bug is fixed: https://pad.lv/1913736. Really
this is a work-around to get the pause/resume test to work.
Related-Bug: #1906280
=> Account for ovn-host leak of ovn-controller pids

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
The commited fix for LP: #1906280 has guard rails to only restart
Open vSwitch on initial install.
However, this is not sufficient as the charm may be deployed to a
unit with a running Open vSwitch data plane as laid out in the OVS
to OVN migration guide [0].
Rework so that we only do the restart when necessary.
0: https://docs.openstack.org/project-deploy-guide/charm-deployment-guide/latest/app-ovn.html#migration-from-neutron-ml2-ovs-to-ml2-ovn
Related-Bug: #1906280
=> Avoid unnecessary restart of OVS on initial deploy

templates/interfaces.yaml
Depending on which PCI address a network interface resolves to
the YAML produced may or may not deserialize into the correct
value.
Encapsulate the address in quotes so that YAML deserialization
always succeeds.
=> Fix rendering of SR-IOV interfaces file

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
To enable safe re-use of the configuration adapter in the OVN
Dedicated Chassis, guard initialization of optional contexts.
Related-Bug: #1906280
=> Only initialize contexts for enabled features

lib/charms/ovn_charm.py, reactive/ovn_chassis_charm_handlers.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
Commit ba9ca99193324c69d6a4e82f64786aea26096140 introduced a
regression that prohibits use of hw-offload due to not initializing
the SR-IOV context. Fix it.
=> Fix missing init of SRIOV context for hw-offload

actions/os_deferred_event_actions.py, lib/charms/ovn_charm.py, unit_tests/__init__.py, unit_tests/test_actions_os_deferred_event_actions.py, unit_tests/test_lib_charms_ovn_charm.py
This adds optional support for deferred events to ovn charms.
For an OVN charm to enable deferred event support it needs to
add the DeferredEventMixin class to the charm class and also
add the action files. Without doing these this change does not
affect a charm.
=> Add support for deferred support to OVN charms.

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
Block restarts of ovs-record-hostname if restarts are not
permitted as it in turn restarts ovs services.
=> Add ovs-record-hostname to deferred service list

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
Run hooks normally when deferred restarts are first enabled. Closes LP bug [1923647](https://bugs.launchpad.net/charm-ovn-chassis/+bug/1923647)
Tested here: https://paste.ubuntu.com/p/tv97Xk2yZB/
=> Initially run hooks when deferred restarts enabled

lib/charms/ovn_charm.py
Do not not restart services when config changes if
enable-auto-restarts=False. This brings the ovn-chassis charms
in-line with the classic charms with respect to restart_on_change.
Closes-Bug: #1923824
=> Honour deferred restarts with restart_on_changed

actions/os_deferred_event_actions.py
Bring the deferred hook actions inline with classic charms.
1) Stop ignoring the 'run-hooks' option when running
'restart-services' action.
2) Make sure any services that need restarting are restarted after
running the 'run-deferred-hooks' action.
Closes-Bug: 1925315
=> Deferred hook actions inline with classic charms

.travis.yml, reactive/ovn_chassis_charm_handlers.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
When used as a subordinate charm, provide chassis certificates to
principal.
This is useful for related charms providing payloads that expect direct
communication with the OVN databases.
While a principal and subordinate charm executes in the same
environment, the payload usually execute under different service
accounts and as such it is impractical and may be less secure to
attempt to provide direct on-disk file access.
Related-Bug: #1918271
=> Provide chassis certificates to principal

config.yaml, lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
By default the CMS will schedule HA chassis groups across all
chassis with bridge- and bridge interface mappings configured.
This configuration option would allow you to influence where
gateways are scheduled when all units have equal bridge- and
bridge interface mapping configuration.
Closes-Bug: #1908377
Closes-Bug: #1934678
Related-Bug: #1848757
=> Add prefer-chassis-as-gw configuration option

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
In order to fix the LP bug#1919481 [0] it was added a try
and except to intanciate the object BridgePortInterfaceMap.
If the config is wrong, it changes the attribute valid_config
to false and this will block the units in the check_mandatory_config
method.
[0] https://bugs.launchpad.net/charm-ovn-chassis/+bug/1919481
=> Block ovn-chassis units with bad config

lib/charms/ovn_charm.py
Ensure that tmpfile config is rendered before calling
systemd-tmpfiles. Without this the install hook can complete before
the tempfile config is rendered, this causes the call to
`systemd-tmpfiles --create` to miss creating
`/run/libvirt-vhost-user`
=> Ensure tmpfile is rendered before systemd-tmpfiles

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
The openstack-release package is added in the Wallaby class as this
package was introduced in the wallaby release to make determination
of the OpenStack release codename easier.
Closes-Bug: #1951462
=> Add BaseWallabyOVNChassisCharm class

lib/charms/ovn_charm.py, reactive/ovn_chassis_charm_handlers.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
When OVN is reconfigured with a new set of certificates, those need to
be updated over the ovsdb-subordinate relation "chassis-certificates"
key. This allows the principle charm (e.g. Octavia charm) to reconfigure
itself with the new certificates.
Closes-Bug: #1952279
=> Update certificates offered over ovsdb-subordinate relation.

config.yaml, lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
Only some dpdk runtime libraries are installed by default, but some
environments may need additional libraries installed. This adds an
option to allow the user to specify additional dpdk runtime libraries
via a config option `dpdk-runtime-libraries`.
Closes-Bug: #1936850
=> Allow additional dpdk runtime libraries to be installed

config.yaml, lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
Review on gerrit with CI results: https://review.opendev.org/c/x/charm-ovn-chassis/+/784557
* config.yaml
Added pmd-cpu-set as a config option.
* lib/charms/ovn_charm.py:
Added the ability to set pmd-cpu-mask in the other_config record of the
open_vswitch table. When an overlap is detected with dpdk-lcore-mask,
charm is set to blocked state with a message asking to fix the overlap.
Related-Bug: #1905416
=> Add setting pmd-cpu-mask via config option

config.yaml
Following the implementation change to allow the use of OVS defaults if the config option is not set, I forgot to update the config option description in config.yaml.
=> Fix description of pmd-cpu-set config option

config.yaml, lib/charms/ovn_charm.py, test-requirements.txt, unit_tests/test_lib_charms_ovn_charm.py, wheelhouse.txt
This option can be used to specify a device holding a card serial number
of a networking controller present in its Vital Product Data (VPD) to
enable SmartNIC DPU support.
Currently the format only supports devices on the 'pci' bus with device
and vendor ids specified. The schema could be extended to support more
buses and parameters in the future.
Config validation errors are now accumulated in the config adapter and
then merged together to form the final status message for a unit.
=> Add a new option: vpd-device-spec

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
If config.rendered is not set it means that configure_ovs hasn't run
yet for the first time. This change allows to run install and
configure_ovs method until the first installation is not completed.
Closes-Bug: 1943970
=> Ensure that deferred events don't break install

unit_tests/test_lib_charms_ovn_charm.py, wheelhouse.txt
Due to the linked bug below, jsonschema >=4.6 now requires
hatchling to build the jsonschema module. In reactive charms, this
happens at install time, but the charm build tool (using pip) doesn't
detect the build dependency for jsonschema.  Therefore, for the moment,
pin the dependency until a more strategic solution is found.
Closes LP Bug: #1987702
=> Pin jsonschema to < 4.6

lib/charms/ovn_charm.py
0851229ef96216a97ee9d072cbb13afb38c63c0a renamed the method
ovs_dpdk_cpu_overlap_check to _ovs_dpdk_cpu_overlap_check while one of
the usages of it was not updated to match.
=> Fix a renamed method call

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
2ef7f9ae209d5895bab6d142678e59c8300c8440 fixed the naming but the method
is on the config adapter not on the charm class. At the same time, the
this code path was not covered by unit tests which is why the issue was
not caught automatically.
=> Fix the overlap method invocation

lib/charms/ovn_charm.py, reactive/ovn_chassis_charm_handlers.py, unit_tests/test_lib_charms_ovn_charm.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
On some busy cloud deployments, it has been reported that the nodes
hosting the ovn-chassis are getting their nf-conntrack tables full
and starting to drop connections. The reason is that GENEVE uses
source port randomization, and the number of "unique" flows is high
from the nf-conntrack's perspective. This is no surprise since flows
are usually identified with their five-tuple (srcip/[srcport]/dstip/dstport/tproto)
by network elements, and GENEVE is leveraging this fact to have an
even distribution in load-balancing systems in between ([*]). The
randomization causes the nf_conntrack table to be flooded with many
GENEVE flows, eventually leading to connection drops in a busy
environment. As there is no particular reason and benefit to track
these flows at the moment, the solution is to …
=> Add iptables NOTRACK rules for excluding GENEVE traffic from nf_conntrack

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
A bridge interface mapping may be set to an empty string which was not
previously handled as invalid config - instead it resulted in an empty
BridgeInterfaceMap which was handled by configure_bridges accordingly
and ovn-cms-opts were set.
The regression made it such that ovn-cms-opts were not set in a case of
an empty BridgeInterfaceMap where as this should only happen when there
is an invalid config specified to the charm.
1) Test failure:
https://review.opendev.org/c/x/charm-ovn-dedicated-chassis/+/857878/2#message-37afbdf3f745d77719aa43afe5234aaa87d70468
2) Analysis:
https://review.opendev.org/c/x/charm-ovn-dedicated-chassis/+/857878/comments/ecde1283_4f1ba2c3
3) PDB output:
https://review.opendev.org/c/x/charm-ovn-dedicated-chassis/+/857878/comments/ecde1283_4f1ba2c3
=> Fix a regression introduced in 0851229e

lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
Commit 1bdca14fe91c added support for using the UCA focal-ovn-22.03 pocket by default for new deployments on Focal.
Unfortunately the change missed some required changes for this to work end to end.
Ensure charm works on Focal without any UCA pocket with the `openstack-release` package already intalled.  The behavior of `charms.openstack` is quite different dependning on whether that information is available or not.
Ensure charm is able to detect availability of and to perform payload upgrade on change of source.
Ensure charm does not attempt payload upgrade on charm upgrade. When upgrading from a charm that does not have the `ovn-source` configuration option, the reactive automatic flag
`config.changed.ovn-source` will fire even though it has not changed.  Clear the flag in upgrade-charm …
=> Fix issues with charm and payload upgrade

config.yaml, layer.yaml, lib/charms/ovn_charm.py, metadata.yaml, reactive/ovn_chassis_charm_handlers.py, unit_tests/test_lib_charms_ovn_charm.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
* Install the prometheus-ovs-exporter snap if the relevant option is
set appropriately (to a valid channel rather than an empty string);
* Provide the endpoint details to the prometheus-k8s-operator
scrape_interface compatible relation (app and unit data);
* Remove the snap or ignore steps to install it if the option is set to
an empty string;
* Clear the relation data for individual jobs if the snap is removed.
* the missing property on the adapter was added (it was exercised in
manual functional testing but not added to the final commit by
mistake);
* moved the logic for snap installation into the charm class;
* added unit tests for various snap install/remove/refresh scenarios.
Additionally, remove the unused variable in one of the handlers and use
an instance of the class.
=> Add prometheus-scrape interface

layer.yaml
1ddb668997b4839208b72c1c13db1036f2ec1917 introduced the usage of the
snap layer for the ovs-exporter installation but missed adding the snap
layer to layer.yaml which was present in the manual functional testing.
=> Add the missing snap layer

config.yaml
The current description erronously refers to 'focal-ovn-22.03' as a valid value, while the correct value is 'cloud:focal-ovn-22.03'.
Closes-Bug: #1992592
=> Fix description of ovn-source configuration option

layer.yaml, lib/charms/ovn_charm.py
Some plugs will not be auto-connected due to a policy decision.
https://forum.snapcraft.io/t/allow-use-of-system-files-interface-and-auto-connection-for-prometheus-ovs-exporter-and-prometheus-ovn-exporter/32179
Therefore, we do it in the charm using the infrastructure present in the
snap layer.
The system-files entries in layer-yaml are commented out pending a
review by policy-reviewers at forum.snapcraft.io.
Signed-off-by: Dmitrii Shcherbakov <dmitrii.shcherbakov@canonical.com>
=> Connect ovs-exporter snap interfaces

layer.yaml, lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
Now that the use of system-files interface has been approved and the
prometheus-ovs-exporter snap with the relevant plugs has been released
to the store, devmode usage can be disabled and additional connections
can be made.
Signed-off-by: Dmitrii Shcherbakov <dmitrii.shcherbakov@canonical.com>
=> Enable strict confinement for the ovs exporter

config.yaml
With the components listed in the charm-guide networking /ovn / hwol page [0], this feature is no longer considered to be experimental.
Fix up the wording around requirement for reboot to apply configuration.
Remove mention of the now deprecated `sriov-netplan-shim` service.
0: https://docs.openstack.org/charm-guide/latest/admin/networking/ovn/hardware-offload.html
=> config/description: Drop experimental status for hardware offload

.github/workflows/tests.yaml, tox.ini
One may see the following error:
pep8: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'http_proxy https_proxy INTERFACE_PATH'
=> fix for new Github Actions 22.04 image

.github/workflows/tests.yaml, config.yaml, lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
Please review and merge commit by commit.
=> Add version pinnning option

.github/workflows/tests.yaml, config.yaml, lib/charms/ovn_charm.py, tox.ini
With the components listed in the charm-guide networking /ovn / hwol page [0], this feature is no longer considered to be experimental.
Fix up the wording around requirement for reboot to apply configuration.
Remove mention of the now deprecated `sriov-netplan-shim` service.
0: https://docs.openstack.org/charm-guide/latest/admin/networking/ovn/hardware-offload.html (cherry picked from commit 0597e4effacb7e419b5f36f055f5d9bf1f3452d6)
=> [stable/22.03] config/description: Drop experimental status for hardware offload

config.yaml, lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
Backport support for configuring version pinning. In order to not impose a change of behavior on existing deployments the default value for the option is set to 'true' on the stable branches.
Instrumented test run with these changes can be viewed in https://review.opendev.org/c/x/charm-ovn-chassis/+/902573
=> [22.03] Make version pinning optional

config.yaml, lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
Backport support for configuring version pinning. In order to not impose a change of behavior on existing deployments the default value for the option is set to 'true' on the stable branches.
Instrumented test run with these changes can be viewed in https://review.opendev.org/c/x/charm-ovn-chassis/+/902572 and https://review.opendev.org/c/x/charm-ovn-chassis/+/902571
=> [23.03] Make version pinning optional

lib/charms/ovn_charm.py, tox.ini, unit_tests/test_lib_charms_ovn_charm.py
Backports patches from stable/22.03 required to fix tox and pep8 errors
=> [stable/20.03] Fix ci errors

config.yaml, lib/charms/ovn_charm.py, unit_tests/test_lib_charms_ovn_charm.py
The OVN charms prepared for the upgrade from OVN 20.03 to newer versions by unconditionally enabling version pinning.
Since then we have reached agreement with upstream that rolling upgrades should work when upgrading within the previous upstream LTS version and the next.
Having the pinning enabled may cause unnecessary grief for anyone already upgraded to OVN 22.03.
Add a charm configuration option to allow controlling the version pinning.
Closes-Bug: #2030944
Signed-off-by: Frode Nordahl <frode.nordahl@canonical.com>
(cherry picked from commit f68ecbd10d2109014c67100ec7e7fe8e1823a7ec) (cherry picked from commit 2a61104364a5e0c5b241a514f65b2323475ed96e) (cherry picked from commit bde8c8c7682872c56aa6f2e2693c95ca262b5431)
=> [stable] Make version pinning optional

lib/charms/ovn_charm.py, unit_tests/__init__.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
When the ovsdb relation is departing the hook will fail since it will try to configure ovs while only partial information is available.
Closes-Bug: #1944983
=> Bail out configuring ovs if no OVNSDB available

lib/charms/ovn_charm.py, unit_tests/__init__.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
When the ovsdb relation is departing the hook will fail since it will try to configure ovs while only partial information is available.
Closes-Bug: #1944983
=> [stable/22.03] Bail out configuring ovs if no OVNSDB available

lib/charms/ovn_charm.py, unit_tests/__init__.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py
When the ovsdb relation is departing the hook will fail since it will try to configure ovs while only partial information is available.
Closes-Bug: #1944983
=> [23.03] Bail out configuring ovs if no OVNSDB available

files/dashboards/ovs-exporter-grafana.json, layer.yaml, metadata.yaml, reactive/ovn_chassis_charm_handlers.py, unit_tests/test_reactive_ovn_chassis_charm_handlers.py, wheelhouse.txt
This change allows relating with require-side of cos-agent interface, for example with grafana-agent. grafana-agent charm can be used to expose metrics to prometheus via push API, or to import dashboards to grafana.
This PR also contains full grafana dashboard in separate commit.
=> Grafana agent integration

files/dashboards/ovs-exporter-grafana.json
Grafana dahsboard has an unnecessary "version" in the title which was left over from testing.
=> dashboard: Typo in the title

wheelhouse.txt
Newer versions of rpds_py require rust toolchain
that is not available in Ubuntu Noble.
=> wheelhouse: Restrict rpds_py<0.25
